### PR TITLE
Add setup.py and use cylc.xtriggers namespace

### LINKED ISSUE #3: Add setup.py
We need a basic `setup.py` to support making the external triggers available via `pip install`.

### PR DESCRIPTION
**Pull request by kinow**
Close #3

Still pending some adjustments on `cylc/cylc-flow`, so still a draft. At the moment the `setup.py` has a link to a branch on my own fork, but will edit the commit later to point to cylc-flow at PYPI.

Related branch in cylc-flow: https://github.com/kinow/cylc-flow/tree/remove-xtriggers

### CODE REVIEW

**Comment by matthewrmshin** [comment]
LGTM. :eyeglasses:

**Comment by kinow** [comment]
Tomorrow morning I will finish the work in my `cylc/cylc-flow` branch `remove-xtriggers`, to confirm `wall_clock` still works, and if I do a `pip install .` in this repository, I get the xtriggers installed and available for my suites :crossed_fingers: if that works will promote this pull request and raise sibling pull request to cylc-flow :tada:

**Comment by kinow** [comment]
Testing it with latest version from Cylc Flow. The branch created in my own fork was so that I could remove `cylc.xtriggers` from Cylc, which required moving `cylc.xtriggers.wall_clock` to `cylc.xtriggers_mgr` (for now, there is ongoing discussion about what to do about it https://github.com/cylc/cylc-flow/issues/3116).

Then started with the simplest test for the kept `wall_clock` external trigger, using a newly created virtual environment:

1. Remove the local cache so that I would get the latest git clone from Cylc flow (`rm -rf ~/.cache/pip`)
2. Installed editable cylc-xtriggers (`pip install -e .`)
3. Tested imports (`python -c 'import cylc;import cylc.xtriggers;'`)
4. Registered the functional test `00-wall_clock` workflow
5. Executed it with `cylc run --no-detach 00-wall_clock -s START=$(date +%Y%m%dT%H) -s HOUR=$(date +%H) -s OFFSET="PT0S"`:

```
            ._.                                                       
            | |                 The Cylc Suite Engine [8.0a0]         
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY.
      .___! |              It is free software, you are welcome to    
      !_____!             redistribute it under certain conditions;   
2019-05-02T15:44:20+12:00 INFO - Suite server: url=tcp://kinow-VirtualBox:43083/ pid=10340
2019-05-02T15:44:20+12:00 INFO - Run: (re)start=0 log=1
2019-05-02T15:44:20+12:00 INFO - Cylc version: 8.0a0
2019-05-02T15:44:20+12:00 INFO - Run mode: live
2019-05-02T15:44:20+12:00 INFO - Initial point: 20190502T1500+12
2019-05-02T15:44:20+12:00 INFO - Final point: 20190502T1500+12
2019-05-02T15:44:20+12:00 INFO - Cold Start 20190502T1500+12
2019-05-02T15:44:20+12:00 INFO - clock xtrigger satisfied: clock = [xtrigger-func cmd]
2019-05-02T15:44:20+12:00 INFO - [foo.20190502T1500+12] -submit-num=01, owner@host=kinow-VirtualBox
2019-05-02T15:44:21+12:00 INFO - [client-command] put_messages kinow@kinow-VirtualBox:cylc-message
2019-05-02T15:44:21+12:00 INFO - [foo.20190502T1500+12] status=ready: (internal)submitted at 2019-05-02T15:44:21+12:00 for job(01)
2019-05-02T15:44:21+12:00 INFO - [foo.20190502T1500+12] -health check settings: submission timeout=None
2019-05-02T15:44:21+12:00 INFO - [foo.20190502T1500+12] status=submitted: (received)started at 2019-05-02T15:44:21+12:00 for job(01)
2019-05-02T15:44:21+12:00 INFO - [foo.20190502T1500+12] -health check settings: execution timeout=None
2019-05-02T15:44:21+12:00 INFO - [client-command] put_messages kinow@kinow-VirtualBox:cylc-message
2019-05-02T15:44:22+12:00 INFO - [foo.20190502T1500+12] status=running: (received)succeeded at 2019-05-02T15:44:21+12:00 for job(01)
2019-05-02T15:44:22+12:00 INFO - Suite shutting down - AUTOMATIC
2019-05-02T15:44:22+12:00 INFO - DONE
```

So first simple test passed.

Important to note that on the branch in my fork of cylc-flow, I **had to merge the work-in-progress CYLC_DIR pull request** (https://github.com/cylc/cylc-flow/issues/3134). That was because in the virtual environment I got the error:

```
/home/kinow/cylc-run/00-wall_clock/log/job/20190502T1500+12/foo/01/job: line 38: /home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/lib/cylc/job.sh: No such file or directory
/home/kinow/cylc-run/00-wall_clock/log/job/20190502T1500+12/foo/01/job: line 39: cylc__job__main: command not found
```

Just in case anyone has the same issue :+1: 

The final test will be to execute a suite that uses one of the other external triggers from `cylc.xtriggers`, that now resides in this module, and are not present `cylc-flow` (from my forked repo).

**Comment by kinow** [comment]
Registered both suites `01-state_suite` and its `upstream` (subfolder). Then validated both:

```
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-xtriggers$ cylc validate --debug 01-suite_state-upstream
2019-05-02T16:04:11+12:00 DEBUG - Loading site/user global config files
2019-05-02T16:04:11+12:00 DEBUG - Reading file /home/kinow/.cylc/global.rc
2019-05-02T16:04:11+12:00 DEBUG - Reading file /home/kinow/cylc-suites/01-suite_state-upstream/suite.rc
2019-05-02T16:04:11+12:00 DEBUG - Expanding [runtime] namespace lists and parameters
2019-05-02T16:04:11+12:00 DEBUG - Parsing the runtime namespace hierarchy
2019-05-02T16:04:11+12:00 DEBUG - Parsing [special tasks]
2019-05-02T16:04:11+12:00 DEBUG - Parsing the dependency graph
2019-05-02T16:04:11+12:00 DEBUG - Configuring internal queues
Valid for cylc-8.0a0
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-xtriggers$ cylc validate --debug 01-suite_state --set=UPSTREAM=$SUITE_NAME_UPSTREAM
2019-05-02T16:04:25+12:00 DEBUG - Loading site/user global config files
2019-05-02T16:04:25+12:00 DEBUG - Reading file /home/kinow/.cylc/global.rc
2019-05-02T16:04:25+12:00 DEBUG - Reading file /home/kinow/cylc-suites/01-suite_state/suite.rc
2019-05-02T16:04:25+12:00 DEBUG - Processing with Jinja2
2019-05-02T16:04:25+12:00 DEBUG - Setting Jinja2 template variables:
	+ UPSTREAM=01-suite_state-upstream
2019-05-02T16:04:25+12:00 DEBUG - Expanding [runtime] namespace lists and parameters
2019-05-02T16:04:25+12:00 DEBUG - Parsing the runtime namespace hierarchy
2019-05-02T16:04:26+12:00 DEBUG - Parsing [special tasks]
2019-05-02T16:04:26+12:00 DEBUG - Parsing the dependency graph
2019-05-02T16:04:26+12:00 DEBUG - Configuring internal queues
Valid for cylc-8.0a0
```

Then started the upstream suite followed by the other suite:

```
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-xtriggers$ cylc run 01-suite_state-upstream
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-xtriggers$ cylc run --set=UPSTREAM=01-suite_state-upstream --no-detach 01-suite_state
            ._.                                                       
            | |                 The Cylc Suite Engine [8.0a0]         
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY.
      .___! |              It is free software, you are welcome to    
      !_____!             redistribute it under certain conditions;   
2019-05-02T16:06:36+12:00 INFO - Suite server: url=tcp://kinow-VirtualBox:43072/ pid=11964
2019-05-02T16:06:36+12:00 INFO - Run: (re)start=0 log=1
2019-05-02T16:06:36+12:00 INFO - Cylc version: 8.0a0
2019-05-02T16:06:36+12:00 INFO - Run mode: live
2019-05-02T16:06:36+12:00 INFO - Initial point: 2011
...
2019-05-02T16:07:03+12:00 WARNING - suite timed out after inactivity for PT10S
2019-05-02T16:07:03+12:00 ERROR - Abort on suite inactivity is set
	Traceback (most recent call last):
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 258, in start
	    self.run()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 1534, in run
	    self.timeout_check()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 1198, in timeout_check
	    self.check_suite_inactive()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 1613, in check_suite_inactive
	    raise SchedulerError('Abort on suite inactivity is set')
	cylc.scheduler.SchedulerError: Abort on suite inactivity is set
2019-05-02T16:07:03+12:00 ERROR - Suite shutting down - Abort on suite inactivity is set
2019-05-02T16:07:03+12:00 INFO - DONE
````

The test in Cylc is programmed to expect this suite to fail, and to have the text "WARNING - suite timed out after inactivity for PT10S" in the logs (which is present).

So it worked! :tada: 

To complete this test, I did the following:

1. Renamed `suite_state` in my IDE (remember, the project was installed as an editable distribution, so the modules are "linked" to what I see in my IDE).

image

2. Started the upstream suite, followed by starting the other suite. Here's the results this time, after `suite_state` was renamed to `ssuite_state`:

```
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-xtriggers$ cylc run --set=UPSTREAM=01-suite_state-upstream --no-detach 01-suite_state
            ._.                                                       
            | |                 The Cylc Suite Engine [8.0a0]         
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY.
      .___! |              It is free software, you are welcome to    
      !_____!             redistribute it under certain conditions;   
2019-05-02T16:11:10+12:00 ERROR - xtrigger function not found: suite_state
	Traceback (most recent call last):
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/subprocpool.py", line 52, in get_func
	    mod_by_name = __import__(mod_name, fromlist=[mod_name])
	ModuleNotFoundError: No module named 'suite_state'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/config.py", line 2078, in load_graph
	    if not callable(get_func(xtrig.func_name, self.fdir)):
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/subprocpool.py", line 57, in get_func
	    mod_by_name = __import__(mod_name, fromlist=[mod_name])
	ModuleNotFoundError: No module named 'cylc.xtriggers.suite_state'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 256, in start
	    self.configure()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 399, in configure
	    self.load_suiterc()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/scheduler.py", line 982, in load_suiterc
	    share_dir=self.suite_share_dir,
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/config.py", line 548, in __init__
	    self.load_graph()
	  File "/home/kinow/Development/python/workspace/cylc-xtriggers/venv/lib/python3.7/site-packages/cylc/config.py", line 2084, in load_graph
	    f"xtrigger function not found: {xtrig.func_name}")
	cylc.exceptions.SuiteConfigError: xtrigger function not found: suite_state
2019-05-02T16:11:10+12:00 CRITICAL - Suite shutting down - xtrigger function not found: suite_state
2019-05-02T16:11:11+12:00 INFO - DONE
SuiteConfigError: xtrigger function not found: suite_state
```

So looks like this `setup.py` is working! :fireworks:

**Review by ColemanTom — APPROVED** [review]
This all looks/sounds good from my limited knowledge of this area.

**Comment by kinow** [comment]
Updated to use `cylc.flow` package now instead of just `cylc`. Repeated the tests above on a local branch of `cylc-flow` that merges the changes for `cylc.flow` (https://github.com/cylc/cylc-flow/pull/3135) and the changes from the previous changes here. No issues found so far.

**Comment by kinow** [comment]
One approval by @ColemanTom and one by @matthewrmshin before I added a few more changes. I think this one can be merged as the project is new/small? Any objections? Or if anybody would like to have another look :+1:

**Comment by matthewrmshin** [comment]
Does this project has integration with Travis CI, etc? Or is this PR the prerequisite for that?

**Comment by kinow** [comment]
I think it will be eadier to build it on travis with dependencies installed in travis with pip/setuptools.

**Review by matthewrmshin — APPROVED** [review]

**Pull request merged**
